INSERT INTO USER (USER_EMAIL, USER_NICKNAME, PASSWORD, IS_ACTIVE) VALUES ('aa@aa.com', 'bb', 'aa', 'Y');
INSERT INTO USER (USER_EMAIL, USER_NICKNAME, PASSWORD, IS_ACTIVE) VALUES ('dd@dd.com', 'bb', 'dd', 'N');

INSERT INTO TAG (TAG_ID, TAG_NAME, IS_ACTIVE) VALUES (1, 'Spring', 'Y');
INSERT INTO TAG (TAG_ID, TAG_NAME, IS_ACTIVE) VALUES (2, 'Hibernate', 'Y');
INSERT INTO TAG (TAG_ID, TAG_NAME, IS_ACTIVE) VALUES (3, '테스트', 'Y');
INSERT INTO TAG (TAG_ID, TAG_NAME, IS_ACTIVE) VALUES (4, 'Java', 'Y');